name: Terramate Apply

on:
  push:
    branches: [ master ]
    paths:
      - 'terraform/**'
      - '**.tm.hcl'
      - '.github/workflows/terramate-apply.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terramate-apply:
    name: 'Terramate Apply'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      - name: Setup Terramate
        uses: terramate-io/terramate-action@v1
        with:
          version: 0.13.0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Terramate Login to Cloud
        run: |
          terramate cloud login --token ${{ secrets.TERRAMATE_CLOUD_TOKEN }}
        env:
          TM_CLOUD_ORGANIZATION: aws-infra-terraform
          # The token should be added as a GitHub secret named TERRAMATE_CLOUD_TOKEN
      
      - name: Terramate List Stacks
        run: terramate list stacks
      
      - name: Terramate Apply
        run: |
          # Initialize all stacks
          terramate run -- terraform init -input=false
          
          # Apply changes with auto-approval
          terramate run --terramate-cloud-deployment=true -- terraform apply -auto-approve -input=false
        
      - name: Notify Terramate Cloud of Deployment Completion
        run: |
          terramate cloud deployment complete
        env:
          TM_CLOUD_ORGANIZATION: aws-infra-terraform
